version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-polimundo
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql-polimundo
    restart: always
    environment:
      MYSQL_DATABASE: polimundo
      MYSQL_USER: polimundo
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: admin.root
    ports:
      - 33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-polimundo
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel

networks:
  laravel:
